# Generated by Django 4.0.4 on 2022-06-08 06:45

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MiaB', '0002_rename_date_memory_date_rename_title_memory_title_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='memory',
            name='date',
            field=models.DateField(blank=True, default=datetime.date.today),
        ),
    ]
